---
theme: light
jwt_secret: a_very_important_secret  # Change this!
default_redirection_url: https://auth.yourdomain.com

server:
  host: 0.0.0.0
  port: 9091

log:
  level: info
  format: text

totp:
  issuer: yourdomain.com  # Change this!
  period: 30
  skew: 1

authentication_backend:
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      key_length: 32
      salt_length: 16
      memory: 1024
      parallelism: 8

access_control:
  default_policy: deny
  rules:
    - domain: auth.yourdomain.com  # Change this!
      policy: bypass
    - domain: "*.yourdomain.com"  # Change this!
      policy: one_factor

session:
  name: authelia_session
  secret: unsecure_session_secret  # Change this!
  expiration: 12h
  inactivity: 45m
  domain: yourdomain.com  # Change this!

regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m

storage:
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt
