---
users:
  homeadmin:  # Change this username
    displayname: "Home Admin"
    password: "$argon2id$v=19$m=65536,t=3,p=4$CHANGE_THIS_PASSWORD_HASH"  # Generate with authelia crypto hash command
    email: your.email@example.com  # Change this
    groups:
      - admins
